name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
        REGISTRY: ghcr.io
        IMAGE_NAME: ${{ github.repository }}
        VERSION: latest
        PYTHON_VERSION: 3.9
        LISTEN_PORT: 8501
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}      

    - name: Build and Push Docker image
      run: |
        docker buildx build \
          -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }} \
          --build-arg pyver=${{ env.PYTHON_VERSION }} \
          --build-arg listen_port=${{ env.LISTEN_PORT }} \
          --no-cache .
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}

    - name: Log out from GitHub Container Registry
      run: docker logout ghcr.io